DYJetsToLL_M-50_HT-100to200:
  nsplit: 1
DYJetsToLL_M-50_HT-1200to2500:
  nsplit: 1
DYJetsToLL_M-50_HT-200to400:
  nsplit: 1
DYJetsToLL_M-50_HT-2500toInf:
  nsplit: 1
DYJetsToLL_M-50_HT-400to600:
  nsplit: 1
DYJetsToLL_M-50_HT-600to800:
  nsplit: 1
DYJetsToLL_M-50_HT-70to100:
  nsplit: 1
DYJetsToLL_M-50_HT-800to1200:
  nsplit: 1
GluGluHToWWToLNuQQ:
  nsplit: 1
ST_s-channel_4f_leptonDecays:
  nsplit: 5
ST_t-channel_antitop_5f_InclusiveDecays:
  nsplit: 5
ST_t-channel_top_5f_InclusiveDecays:
  nsplit: 5
ST_tW_antitop_5f_inclusiveDecays:
  nsplit: 1
ST_tW_top_5f_inclusiveDecays:
  nsplit: 1
SingleElectron:
  nsplit: 9
SingleMuon:
  nsplit: 9
TTTo2L2Nu:
  nsplit: 9
TTToHadronic:
  nsplit: 9
TTToSemiLeptonic:
  nsplit: 9
VBFHToWWTo2L2Nu:
  nsplit: 1
VBFHToWWToLNuQQ:
  nsplit: 1
WJetsToLNu_HT-100To200:
  nsplit: 1
WJetsToLNu_HT-1200To2500:
  nsplit: 1
WJetsToLNu_HT-200To400:
  nsplit: 1
WJetsToLNu_HT-2500ToInf:
  nsplit: 1
WJetsToLNu_HT-400To600:
  nsplit: 1
WJetsToLNu_HT-600To800:
  nsplit: 1
WJetsToLNu_HT-800To1200:
  nsplit: 1
WW:
  nsplit: 1
WZ:
  nsplit: 1
ZZ:
  nsplit: 1
